### ISSUE TITLE
Add a Captcha

### ISSUE THREAD

**Issue by hettiger** [hettiger/larapress#19]
Add a Captcha to secure resetting a password

**Comment by hettiger** [comment]
### Idea

Could become a nice filter to use for more than just the resetting password feature:
1. Theres some action that requires a check if the current user is actually human
2. Add a `force.human` filter to the controller method
3. Whenever the filter is called it checks the session to see if a captcha has been solved in the last 10 minutes
4. If it has been solved proceed
5. If not redirect back with `Session::flash('error', '...')`

The captcha could become a partial view that can be included anywhere. Checking the captcha could be accomplished by an ajax request. On success the captcha disappears leaving a success message.

**Comment by hettiger** [comment]
### Possible Captcha Solutions
- [x] https://github.com/greggilbert/recaptcha (MIT)
- [x] https://github.com/Latrell/Captcha (MIT japanese? PHPDoc blocks)
- [x] https://github.com/wikichua/captcha-laravel
- [x] https://github.com/mewebstudio/captcha
- [x] Custom

**Checked = Reviewed**

**Comment by hettiger** [comment]
Will use greggilbert/recaptcha

**Comment by hettiger** [comment]
#### TODO
- [x] Get the correct api url from php for the javascript
- [x] Allow submission by hitting the enter key
- [x] Add better messages and translations for them
- [x] Add the timer functionality
- [x] Add the Filter
- [x] Make it actually look good
- [x] Add a no JavaScript fallback
- [x] Refactoring
- [x] Write tests
- [x] Add docs

**Comment by hettiger** [comment]
Added tests for the api controllers.

Look at the [comparison](https://github.com/larapress-cms/larapress/compare/develop...feature%2Fcaptcha) to see what's missing.

**Warning: There might be some old tests that'll need an update!**

**Comment by hettiger** [comment]
### TODO
- [x] Update existing docs (filters.md, configuration.md)
