### ISSUE TITLE
Add password reset functionality

### ISSUE THREAD

**Issue by hettiger** [hettiger/larapress#5]

**Comment by hettiger** [comment]
#### TODO
- [x] Add a Helper function to throw 404 errors the BaseController way
- [x] Refactor HomeController@getSendNewPassword()
- [x] Translate the emails
- [x] Write tests
- [x] Test everything manually
